#!/usr/local/bin/php
<?php

$lookingFor   = 'artisan';
$commandToRun = 'artisan --ansi';

$dir = explode('/', getcwd());

$arguments = $argv;
array_shift($arguments);
$artisanCommand = implode(' ', $arguments);

$i=0;
while (sizeof($dir) >= 2 && $i<20) {
    $i++;
    $levelUp = implode('/', $dir);
    $artisanFile = $levelUp . '/' . $lookingFor;

    array_pop($dir);
    if (file_exists($artisanFile) && is_file($artisanFile)) {
        break;
    }
}

$exec = "php {$levelUp}/{$commandToRun} {$artisanCommand}";
passthru($exec);
